- name: install remi release
  ansible.builtin.package: #yum install https://rpms.remirepo.net/enterprise/remi-release-8.rpm # check package will work not
    name: https://rpms.remirepo.net/enterprise/remi-release-8.rpm
    state: present
    disable_gpg_check: true

# - name: install redis
#   ansible.builtin.shell: amazon-linux-extras install redis6 -y
- name: install redis
  ansible.builtin.package:
   name: redis6
   state: present

- name: allow remote connections
  ansible.builtin.replace:
    path: /etc/redis6/redis6.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'

- name: start and enable redis
  ansible.builtin.service:
    name: redis6
    state: restarted
    enabled: yes