# - name: install git
#   ansible.builtin.import_role:
#     name: common
#     tasks_from: git

- name: app setup
  ansible.builtin.import_role:
    name: common
    tasks_from: appsetup

- name: install nodejs 
  ansible.builtin.import_role:
    name: common
    tasks_from: nodejssetup

- name: setup systemd
  ansible.builtin.import_role:
    name: common
    tasks_from: systemd