# - name: install git and go lang
#     ansible.builtin.package:
#       name: "{{ item }}"
#       state: present
#     loop:
#     - git
#     - golang

- name: install go lang
  ansible.builtin.package:
    name: golang
    state: present


- name: install dependencies and build
  ansible.builtin.command: "go build -o my{{component}}"
  args:
    chdir: /app