- name: download java 19
  ansible.builtin.get_url: 
    url: https://download.oracle.com/java/19/archive/jdk-19.0.2_linux-x64_bin.rpm
    dest: /tmp/jdk-19.0.2_linux-x64_bin.rpm

- name: install java
  ansible.builtin.package:
    name: /tmp/jdk-19.0.2_linux-x64_bin.rpm
    state: present
    disable_gpg_check: true

- name: execute permissions
  ansible.builtin.file:
    path: /app/gradlew
    mode: +x

- name: download repos and install dist
  ansible.builtin.shell:
    cmd: "{{ item }}"
  with_items: 
  - "./gradlew downloadRepos"
  - "./gradlew installDist"
  args:
    chdir: /app

- name: create a directory
  ansible.builtin.file:
    path: /opt/cprof
    state: directory

- name: Download Cloud Profiler Java Agent tarball
  ansible.builtin.get_url:
    url: https://storage.googleapis.com/cloud-profiler/java/latest/profiler_java_agent.tar.gz
    dest: /opt/cprof/profiler_java_agent.tar.gz

- name: Extract Cloud Profiler Java Agent
  ansible.builtin.unarchive:
    src: /opt/cprof/profiler_java_agent.tar.gz
    dest: /opt/cprof
    remote_src: yes 

- name: Remove the tarball (optional)
  ansible.builtin.file:
    path: /opt/cprof/profiler_java_agent.tar.gz
    state: absent

